### ISSUE TITLE
Add notification while loggin in by e-mail ("I already have an identity")

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me-ios#19]
There is missing a notification if the user wants to log in by e-mail.

1. After the e-mail is send to the e-mail addres the user doesnt get any notification on what to expect.

--------------------------------

1. Add notifciation after the link is send to the e-mail adress.

	- English: "Please click the link you've received to complete the procces"
	- Dutch: "Klik op de link die u per e-mail is toegestuurd om in te loggen"

**Comment by jknnr** [comment]
@GerbenBosschieter please assign me to all the issues about the Me app :)

**Comment by jknnr** [comment]
fixed
