### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by jamalv** [teamforus/me-ios#2]
The screens should look and function well on any iPhone screen size

**Comment by danrminds** [comment]
We will proceed with responsiveness after all screens are implemented for 1 screen size.

**Comment by jknnr** [comment]
@jamalv not relevant. can I close?

**Comment by jknnr** [comment]
not relevant

**Comment by GerbenBosschieter** [comment]
I don't get why this isn't relevant ?

**Comment by jknnr** [comment]
I was wrong to say "not relevant". Its just too abstract. Lets make just a concrete tasks about each screen.
