### ISSUE TITLE
placeholder for avatar should be me logo

### ISSUE THREAD

**Issue by danrminds** [teamforus/me-ios#26]

**Comment by maxvisser** [comment]
this one ![image](https://user-images.githubusercontent.com/10818702/47084060-c28c0280-d212-11e8-96e7-03a71215498b.png)
should be replaced by me logo


looks also a bit weird in our new flyer for providers (no uniformity):
![image](https://user-images.githubusercontent.com/10818702/47084086-d6cfff80-d212-11e8-92c4-5ed74eef060a.png)

**Comment by jknnr** [comment]
fixed
