### ISSUE TITLE
What's the location of these warning messages?

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me-ios#30]
I want to translate these error messages, but can't find them. Who knows?
I have a feeling its generated by the back-end

![img_0028](https://user-images.githubusercontent.com/38419514/47095674-f7598300-d22d-11e8-93d3-9037e411655a.PNG)

**Comment by danieltcacenco** [comment]
that message come from server.

**Comment by danieltcacenco** [comment]
> I want to translate these error messages, but can't find them. Who knows?
> I have a feeling its generated by the back-end
> 
> ![img_0028](https://user-images.githubusercontent.com/38419514/47095674-f7598300-d22d-11e8-93d3-9037e411655a.PNG)

that message come from server.
