### ISSUE TITLE
Crash on product voucher

### ISSUE THREAD

**Issue by jamalv** [teamforus/me-ios#36]
When you purchase a product voucher, the app crashes.

## To reproduce:
Activate an account on https://dev.zuidhorn.forus.link/#!/ enter a voucher code and purchase a product voucher. When you open the app on the voucher page it crashes.

@GerbenBosschieter, could you paste a couple activation codes here?

**Comment by maxvisser** [comment]
@gerben i think if you make more vouchers its ok to test this on dev. As it will not interfere with the test at qnh

**Comment by GerbenBosschieter** [comment]
I will

**Comment by GerbenBosschieter** [comment]
@jamalv 
@teamforus/development 

If you use one of these activation codes. Pleas edit my comment and delete or cross out the code. So it's clear for people with one they can use.

de43-3389
4d70-7611
fa41-23e9
c7b1-5f36
e9a4-fae0
d829-6ae3
6bf8-dd3f
7f38-730a
9ad3-5b86
b739-35f6

**Comment by GerbenBosschieter** [comment]
@max, with more vouchers I assume you just mean more activation codes right ? Or do you really mean a fund. Cause thats something we turned of.
