### ISSUE TITLE
Cant pass the login code screen after restoring account.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me-ios#37]
If I have an identity and want to log in with another device, it will load my identity. But asks me to fill in the passcode that I didn't even created yet. 

Can't go back or restart the app to fix this. 
Its stuck at the passcode screen.

**Comment by jknnr** [comment]
on it

**Comment by GerbenBosschieter** [comment]
@jknr is this issue fixed? I havent seen a commit about this. But the problem didn’t occur anymore.

I Will try to reproduce it

**Comment by jknnr** [comment]
Not fixed, it works on android. iOS will fix tomorrow

**Comment by jknnr** [comment]
fixed
