### ISSUE TITLE
Screen doesn't allow me to complete a transaction.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me-ios#38]
**Description**

The screen after I've scanned a product or normal voucher doesn't allow me to continue.
After I click on "amount" or "notes" textfields to enter some data the keyboard is displayed.

I can''t hide the keyboard after it's displayed and can't scroll the background to continue.
The screen blocks user  to proceed with the payment. 

![img_0033](https://user-images.githubusercontent.com/38419514/47614479-b0c31e80-daa0-11e8-8170-78c800f0706b.PNG)

**Comment by jknnr** [comment]
fixed
