### ISSUE TITLE
Some problems with the "change 4 digit passcode" screen.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me-ios#40]
**Problem**

The screen that is shown after choose "change 4 digit passcode" has some issues on different screen sizes. For example: iPhone 6 will display the circles like there are chopped
![img_0034](https://user-images.githubusercontent.com/38419514/47614614-f2ed5f80-daa2-11e8-9494-69bf8422fd3b.PNG)

And the iPhone SE will not even display the circles. So the user will not receive any feedback when changing the code.

![img_0447](https://user-images.githubusercontent.com/38419514/47614628-24662b00-daa3-11e8-94d0-abd4c2b1f7d0.PNG)

**Comment by jknnr** [comment]
fixed
