### ISSUE TITLE
Open currency animation

### ISSUE THREAD

**Issue by jamalv** [teamforus/me-ios#5]
Animation when opening a currency should go sideways, with possibility to swipe back using the gesture. See mail as example:

[ScreenRecording_05-20-2018 11-37-46.MP4.zip](https://github.com/teamforus/me-ios/files/2020210/ScreenRecording_05-20-2018.11-37-46.MP4.zip)

**Comment by jknnr** [comment]
@jamalv not relevant. can I close?

**Comment by jknnr** [comment]
not relevant
