### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by jamalv** [teamforus/me-ios#8]
Localize the app for Dutch and English

@dan, can we deliver both the English and Dutch designs for the first screens?

**Comment by jamalv** [comment]
Clarification: the app should look at your iOS language preferences and show the texts in Dutch or in English depending on your setting. For now the main focus is on Dutch, but it would be good to also support English right away.

[Apple documentation](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/Introduction/Introduction.html)

**Comment by danrminds** [comment]
I will prepare the design files in both languages.

**Comment by jknnr** [comment]
done
